### ISSUE TITLE
"ala" in ken...la condition statement causes toki ike

### ISSUE THREAD

**Issue by deltatekalec** [dmadisetti/sona.js#2]
The following returns `Error: toki ike: Wan,li,1,ala (2)`:
```
ijo Wan li 1

ken Wan li 1 ala la nanpa Wan
```
I am on the latest version with postfix ala, but just to make sure I tested it with prefix ala and it returns the same. This may be due to L.indexOf(la) incorrectly taking the "la" in "ala" to be the end of the expression.

**Comment by dmadisetti** [comment]
Yeah, nested expressions are not supported (including negation). It's pretty annoying- but there's a lot of baggage, order of operations, capturing multiple tokens etc.. (Brackets) could help, but then I think it breaks the way sona looks when written. There could be an exception for 2 token expressions- but I think it still requires an annoying work around.

There was a suggestion for multiterm expressions:

`ijo Ilo li mute e Wan en Tu en Luka`,

which is actually pretty straightforward to implement.
That wouldn't fix your issue either, but some of the underlying structure would make it easier to fix. Maybe for version 2?

The best you can do is assign the negation to another variable and use that.

**Comment by deltatekalec** [comment]
I see what you mean. I think the best thing to do, if you decide to add support for something like this, would be to just have an exception for negation. I agree that brackets would break the aesthetic and without them expressions would get cluttered really quickly. Being able to stick one "ala" at the end of your expression though would save you some temp variables, and it doesn't seem too difficult to implement, but I'll defer to you on that judgement.

I also like the idea for multiterm expressions, it would definitely help alleviate some of the issues caused by lack of nesting.

**Comment by dmadisetti** [comment]
https://github.com/dmadisetti/sona.js/tree/namako supports this. Required a change to the tokenizer, and also it doesn't support `number ala`,  just `Variable ala`, which I think is good.

**Comment by dmadisetti** [comment]
closed by #3
